version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=1234567
    ports:
      - 5432:5432
    

  web:
    build: ./api
    ports:
      - '5533:5533'
    restart: always

    